use std::collections::HashMap;

fn main() {
    //Integers were generated by Random.org. There are 103 total integers, 
    //with a possible range from -128 to 127.
    let mut nums: Vec<i8> = vec![100, -113, -4, -109, -75, 26, -85, 8, -123, 127, -3, 
    -28, -6, -102, -69, -4, 80, -93, 45, -89, 92, -4, 84, -9, -44, -87, 23, -44, 
    -41, 115, 30, 20, -84, -23, -97, -117, 28, 97, -103, 23, -16, -80, -29, 66, 30, 
    90, -47, -62, 41, 31, 25, 112, 113, 89, -86, 10, -30, 9, -103, 110, -41, 46, 42,
    -36, -18, -44, -110, -60, -9, 73, -17, 54, -88, 22, -104, 104, 40, 66, 31, 48,
    -20, -1, -81, -98, 30, -29, -106, -98, -60, 90, 72, -47, 94, -99, 59, 66, -92,
    111, -37, 83, 3, 6, 62];

    nums.sort();

    let mut med_value: i8 = -128;
    let med_target = nums.len()/2;

    let mut frequency_map = HashMap::new();
    
    for (i,n) in nums.iter().enumerate(){
        //This updates the HashMap with frequency of each integer
        let current = frequency_map.entry(n).or_insert(0);
        *current += 1;

        //This gets the median value
        if i == med_target {
            med_value = *n;
        }
    };

    let mut max_frequency = 0;
    let mut max_value = -128;

    for (key, value) in frequency_map{
        if value > max_frequency {
            max_frequency = value;
            max_value = *key;
        }
    }

    println!("The Median of these integers is {med_value} and the Mode is {max_value}, which occurs {max_frequency} times.");
}